apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: client
  name: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: client
    spec:
      containers:
      - image: manrodri/client
        name: client
        resources: {}

---
status: {}
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: client
  name: client
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: client
status:
  loadBalancer: {}

---  
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: client
  name: client-svc
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
    nodePort: 30007
  selector:
    app: client
  type: NodePort
status:
  loadBalancer: {}
